devcodemaestro/kindergarten

src/App.js, src/components/common/NavBar.js, src/components/common/SideBar.js, src/hooks/useCustomMove.js
컴포넌트 Navbar를 SideBar로 수정
컴포넌트 Header를 NavBar로 수정
=> add:common 컴포넌트의 파일명 수정과 추가

src/pages/adminPage/GuardianList.js, src/styles/guardianlist.css, src/styles/guardianlist.js
=> feat: 관리자 학부모 리스트 페이지 퍼블리싱 진행중

src/pages/notice/Notice.js
=> feat: 유치원 소식 페이지 기본 레이아웃 구성

src/components/common/NavBar.js, src/components/common/SideBar.js, src/styles/basic.js, src/styles/index.css
=> feat : 공통 css 적용 진행중

src/App.js, src/components/common/SideBar.js
=> feat: route 수정

src/App.js, src/pages/adminPage/AdminPage.js, src/pages/adminPage/GuardianList.js, src/pages/adminPage/StudentCreate.js, src/pages/adminPage/StudentList.js, src/styles/adminstyle/guardianlist.js, src/styles/adminstyle/studentlist.js
=> feat: 학부모 관리 리스트, 원생 관리 리스트, 원생 등록 페이지 퍼블리싱 진행중

src/pages/information/Info.js, src/pages/information/InfoClass.js, src/styles/information/info.css, src/styles/information/info_class.css
=> feat: info 작업중

src/pages/album/Album.js, src/styles/album/album.js
=> fix : 앨범 컴포넌트 CSS 정리중

package-lock.json, package.json, src/components/common/SideMenu.js, src/pages/adminPage/GuardianList.js, src/pages/adminPage/student/StudCreate.js, src/pages/adminPage/student/StudList.js, src/styles/adminstyle/studcreate.js, src/styles/adminstyle/studentlist.js
=> feat: 다음 주소 API 설치 및 연동 작업

src/pages/notice/NoticeDetails.js, src/pages/notice/NoticeList.js, src/pages/notice/NoticeModify.js
=> feat : 유치원 상세페이지 퍼블리싱 및 등록 페이지 진행중

src/components/adminpage/GuardianListComponent.js, src/pages/adminPage/student/StudDetails.js, src/pages/adminPage/student/StudDetailsForm.js, src/pages/adminPage/student/StudList.js, src/styles/adminstyle/studdetailsform.js, src/styles/user/mypage.js
=> feat : 원생 상세 페이지, 원생 상세 등록 페이지 퍼블리싱

src/App.js, src/pages/notice/NoticeDetails.js, src/pages/notice/NoticeList.js, src/pages/notice/NoticeWrite.js
=> feat : 유치원소식 등록 페이지 진행중

src/App.js, src/components/common/ResultModal.js, src/pages/album/Album.js, src/pages/notice/NoticeDetails.js, src/pages/notice/NoticeList.js, src/pages/notice/NoticeModify.js, src/pages/notice/NoticeWrite.js
=> 유치원 소식 상세페이지 수정중

src/pages/notice/NoticeModify.js, src/pages/notice/NoticeWrite.js
=> feat : 유치원 소식 기능 수정

package.json, src/api/notice/notice_api.js
=> feat : Swagger API 데이터 연동 테스트

src/App.js, src/components/album/DetailsAlbum.js, src/components/album/ReadAllAlbum.js, src/components/common/TemporaryData.js, src/pages/album/AlbumDetails.js, src/pages/album/AlbumModify.js, src/pages/album/AlbumWrite.js, src/styles/album/album.js
=> feat : 앨범 상세 퍼블리싱 중

src/components/album/DetailsAlbum.js, src/components/album/LightBox.js, src/styles/album/album.js
feat : 앨범 LightBox 기능 구현하여 Swiper와 결합시킴
=> feat : 앨범 LightBox 기능 구현하여 Swiper와 결합시킴

src/api/notice/notice_api.js, src/components/album/DetailsAlbum.js, src/components/album/ReadAllAlbum.js, src/pages/album/AlbumDetails.js, src/pages/notice/NoticeDetails.js, src/styles/album/album.js, src/styles/basic.js
=> 유치원 소식 상세 데이터 연동 진행중

src/App.js, src/api/notice/notice_api.js, src/pages/notice/NoticeDetails.js
=> feat : 유치원 소식 상세페이지 데이터 연동 진행중

package-lock.json, package.json, src/components/album/DetailsAlbum.js, src/components/common/CommentClassic.js, src/styles/album/album.js
=> feat: 클래식한 댓글기능 추가구현

src/api/adminApi.js, src/api/album/album_api.js, src/api/noticeApi.js, src/components/album/DetailsAlbum.js, src/pages/album/AlbumModify.js, src/pages/album/AlbumWrite.js
=> feat : API 연동 테스트 중

src/api/adminPage/admin_api.js, src/components/adminpage/GuardianListComponent.js, src/components/adminpage/StudListComponent.js, src/pages/adminPage/GuardianList.js, src/pages/adminPage/student/StudCreate.js, src/pages/adminPage/student/StudDetailsForm.js, src/pages/adminPage/student/StudList.js, src/styles/adminstyle/guardianlist.js
한 건 없지만.. 쪼금 건드려서 푸쉬합니당 내일 봬요~!
=> feat: 페이지네이션 css 적용

src/api/config.js, src/api/mainApi.js, src/api/user/userApi.js, src/components/common/NavBar.js, src/components/common/SideMenu.js, src/components/user/mypage/MyPhysicalComponent.js, src/components/user/mypage/MyProfileComponent.js, src/pages/user/MyPage.js, src/pages/user/ParentEdit.js, src/pages/user/SignupForm.js, src/styles/user/mypage.js
=> feat : 마이페이지, 학부모 정보수정 연동 진행중

src/App.js, src/api/album/album_api.js, src/components/album/DetailsAlbum.js, src/components/album/ReadAllAlbum.js, src/components/common/TemporaryData.js, src/pages/album/Album.js, src/pages/album/AlbumDetails.js, src/pages/album/AlbumModify.js, src/pages/notice/NoticeDetails.js
=> feat : API 연동중

src/api/notice/notice_api.js, src/pages/notice/NoticeDetails.js, src/pages/notice/NoticeList.js, src/styles/notice/gallery.css
=> 유치원 소식 페이지 데이터 연동 진행중

src/App.js, src/api/album/album_api.js, src/api/notice/notice_api.js, src/components/album/DetailsAlbum.js, src/components/album/ReadAllAlbum.js, src/components/album/WriteAlbum.js, src/pages/album/Album.js, src/pages/notice/NoticeDetails.js, src/pages/notice/NoticeList.js, src/styles/album/album.js, src/styles/basic.js, src/styles/notice/gallery.css
feat : API 연동 중. Album 전체 리스트와 상세 리스트 get 연동처리 완료
=> feat : API 연동 중. Album 전체 리스트와 상세 리스트 get 연동처리 완료

src/api/notice/notice_api.js, src/pages/notice/NoticeDetails.js, src/pages/notice/NoticeList.js, src/pages/notice/NoticeWrite.js
=> 유치원소식 글쓰기 기능 진행중

src/api/information/informationApi.js, src/api/mainApi.js, src/api/user/userApi.js, src/components/common/NavBar.js, src/components/main/MainAlbumComponent.js, src/components/main/MainNoticeComponent.js, src/components/user/mypage/MyProfileComponent.js, src/pages/Main.js, src/pages/information/Info.js, src/pages/information/InfoClass.js, src/pages/user/Accounts.js, src/pages/user/Login.js, src/pages/user/MyPage.js, src/pages/user/SignupForm.js, src/styles/basic.js, src/styles/information/info.js, src/styles/main.js, src/styles/user/login.js
- 회원가입 전  식별코드 입력페이지 완료
- 부모님 회원가입 진행중
- 마이페이지 식별코드추가, 회원탈퇴 작업 중
화이팅입니다~!!!
=> feat : 메인연동, 유치원소개, 유치원현황 완료, 회원가입 진행중

src/api/notice/notice_api.js, src/pages/notice/NoticeDetails.js, src/pages/notice/NoticeList.js, src/pages/notice/NoticeModify.js, src/pages/notice/NoticeWrite.js
=> feat : 유치원 소식 수정파트 진행중

src/api/notice/notice_api.js, src/pages/notice/NoticeDetails.js, src/pages/notice/NoticeList.js, src/pages/notice/NoticeModify.js
=> feat : 유치원 소식 수정 파트 이미지 데이터 연동 진행중

src/api/notice/notice_api.js, src/pages/notice/NoticeModify.js, src/pages/notice/NoticeWrite.js
=> feat : 유치원 소식 API 연동 글쓰기(POST) 완료

src/api/notice/notice_api.js, src/pages/notice/NoticeModify.js, src/pages/notice/NoticeWrite.js
=> feat : 유치원 소식 PUT 데이터 연동 에러 수정 중

src/api/individualNotice/indivNoticeApi.js, src/api/notice/notice_api.js, src/pages/individualNotice/IndivNotiModify.js, src/pages/individualNotice/IndivNotiWrite.js, src/pages/notice/NoticeModify.js
=> feat : 유치원 소식 수정(PUT) 진행중

src/App.js, src/api/adminPage/admin_api.js, src/api/eduApi.js, src/api/kidApi.js, src/components/adminpage/StudListComponent.js, src/components/user/mypage/MyProfileComponent.js, src/pages/adminPage/student/StudModify.js, src/pages/information/InfoClass.js
아이 프로필 이미지는 통일될 경로로 맞춰놓은거라 엑박이 많이떠용..!
참고 부탁드립니닷
=> feat : 원아 수정 완료, 아이 프로필 이미지 경로 수정

src/api/adminPage/admin_api.js, src/components/adminpage/StudListComponent.js, src/components/user/mypage/MyProfileComponent.js, src/pages/adminPage/GuardianList.js, src/pages/adminPage/student/StudDetails.js, src/pages/adminPage/student/StudDetailsForm.js, src/pages/adminPage/student/StudList.js, src/styles/adminstyle/studentlist.js
=> feat: 관리자페이지 예외처리 및 모달창 정리

src/components/notice/DetailsNotice.js, src/pages/notice/NoticeModify.js, src/pages/notice/NoticeWrite.js
=> 유치원 소식 수정 기능 진행 중

src/components/album/DetailsAlbum.js
=> fix : 앨범 상세부분 모달창 UI 통일

src/components/album/DetailsAlbum.js, src/components/album/WriteAlbum.js
fix : 앨범 등록 모달창 통일 및 20개 이상 업로드 시 경고 모달창 발생
=> fix : 앨범 등록 모달창 통일 및 20개 이상 업로드 시 경고 모달창 발생

src/pages/notice/NoticeWrite.js
=> feat : 모달창 수정중

src/pages/notice/NoticeModify.js, src/pages/notice/NoticeWrite.js
=> feat : 유치원 소식 파트 수정 기능 수정중

src/api/notice/notice_api.js, src/pages/notice/NoticeModify.js
=> 유치원 소식 파트 수정 기능 진행중

src/components/album/ReadAllAlbum.js, src/components/common/NavBar.js, src/pages/album/Album.js, src/pages/information/Info.js, src/pages/information/InfoClass.js, src/styles/adminstyle/guardianlist.js, src/styles/album/album.js, src/styles/basic.js, src/styles/index.css, src/styles/information/info.js, src/styles/main.js, src/styles/ui/buttons.js
=> feat : 유치원소개, 활동앨범 리스트 반응형 작업 완료

src/api/individualNotice/indivNoticeApi.js, src/components/album/DetailsAlbum.js, src/components/album/ModifyAlbum.js, src/components/album/ReadAllAlbum.js, src/components/album/WriteAlbum.js, src/components/common/SideBar.js, src/components/notice/ListNotice.js, src/styles/album/album.js, src/styles/basic.js, src/styles/index.css, src/styles/information/info.js, src/styles/notice/notice.js
=> feat : 오시는길, 활동앨범 반응형 완료, 유치원소식 진행중

src/pages/notice/NoticeModify.js
=> 유치원 소식 수정기능 진행 중

src/api/notice/notice_api.js, src/components/notice/DetailsNotice.js, src/components/notice/ListNotice.js, src/pages/notice/NoticeModify.js
=> feat : 유치원 소식 수정기능 작업중

src/api/album/album_api.js, src/components/album/ModifyAlbum.js
- 앨범 수정 기능 추가
- 모달 창 추가
- 수정 시 1차 경고
- 수정 완료 후 완료 안내
- 최소 1장의 이미지 업로드 경고
=> feat : 활동앨범 수정기능 추가

src/api/config.js, src/api/notice/notice_api.js, src/components/notice/DetailsNotice.js, src/pages/notice/NoticeModify.js
=> feat : 유치원소식 수정기능 진행중(이미지 추가 업로드 완료/이미지 수정삭제 진행중)

src/components/album/ModifyAlbum.js, src/components/album/WriteAlbum.js, src/pages/notice/NoticeModify.js
- 이미지 필수로 추가시에만 수정 가능했던 부분 서버 예외처리 수정 요청하여 수정
- 추가한 이미지를 삭제시 string 값이 서버에 전송되어 오류발생. 예외분기처리하여 해결
=> fix : 앨범 수정 기능 일부 수정

src/pages/individualNotice/IndivNotiList.js, src/pages/information/Info.js, src/styles/individualNotice/ind.js, src/styles/information/info.js, src/styles/user/mypage.js
리스트 안에 내용들은 아직 api 안나와서 나오면 고치겠습니당
=> feat : 알림장 리스트 완료

src/api/config.js, src/api/notice/notice_api.js, src/components/individualNotice/IndWriteComponent.js, src/components/notice/ListNotice.js, src/pages/notice/NoticeModify.js
=> feat : 유치원소식 수정기능 완료. 알림장 글쓰기 퍼블리싱 진행중

src/api/album/album_api.js, src/components/album/ReadAllAlbum.js, src/components/album/WriteAlbum.js, src/pages/album/Album.js
fix : 앨범수정
- 수정 내용 없이 수정 버튼 클릭시 확인 경고 모달처리.
- 앨범 등록,수정의 업로드 영역 height 수정
feat : 검색기능
- 검색 기능 api 생성 및 기능 구현
- 무한스크롤 기능과 충돌 오류 수정.
=> fix : 앨범수정

src/api/individualNotice/indivNoticeApi.js, src/components/individualNotice/IndWriteComponent.js
=> 알림장 등록 중요체크 기능 작업중

src/api/album/album_api.js, src/components/album/ModifyAlbum.js, src/components/album/ReadAllAlbum.js, src/components/album/WriteAlbum.js, src/pages/album/Album.js
- 신규 작성 중 취소 클릭시 확인 모달에서 확인, 취소 선택하도록 변경
- 신규,수정 시 이미지 파일 최소 1개 유지 경고
- 신규 작성 중 취소버튼 클릭시 최소 이미지 갯수 유지 경고와 취소 경고 중복 오류로 수정
- 경고 창 이외 클릭시 이벤트 전파 차단
=> fix : 앨범 모달 수정

src/api/individualNotice/indivNoticeApi.js, src/components/individualNotice/IndWriteComponent.js, src/pages/notice/NoticeWrite.js
=> feat : 알림장 선생님 글쓰기 기능 진행중

package-lock.json, package.json, public/firebase-messaging-sw.js, src/api/user/pushApi.js, src/atoms/pushState.js, src/components/common/NavBar.js, src/fb/fbconfig.js, src/hooks/useCustomLogin.js, src/index.js, src/styles/user/notialarm.js, src/util/jwtUtil.js
- firebase 설치
- recoil 설치
- firebaseToken 갱신 및 전송
- accessToken 권한 별 갱신
=> feat : 웹푸시 기능 진행중

src/api/individualNotice/indivNoticeApi.js, src/components/individualNotice/IndWriteComponent.js
=> feat : 알림장 선생님 글쓰기 기능 완료 후 상세페이지 댓글 기능 작업중

package-lock.json, package.json, src/api/indivAlbum/indivalbum_api.js, src/components/indivAlbum/IndAlbumParentBtn.js, src/components/indivAlbum/IndAlbumTeacherBtn.js, src/components/indivAlbum/MyTag.js, src/components/indivAlbum/ReadAllIndAlbum.js, src/components/indivAlbum/WriteIndivAlbum.js, src/components/individualNotice/IndWriteComponent.js, src/pages/indivalbum/IndivAlbumDetails.js, src/pages/indivalbum/IndivAlbumList.js, src/pages/indivalbum/IndivAlbumWrite.js, src/pages/individualNotice/IndivNotiList.js, src/styles/individualAlbum/indalbum.js, src/styles/individualNotice/inddetail.js
- 삭제
- api 수정 및 연동 완료
- 리스트
- 앨범 당 이미지 5개 미리보기 로딩
- 다섯번째 이미지에 잔여 이미지 갯수 오버레이 처리
- 상세
- 이미지 Masonry-gird 라이브러리 구현
=> feat : 추억앨범 API 연동 중

src/api/indivAlbum/indivalbum_api.js, src/components/album/ModifyAlbum.js, src/components/album/ReadAllAlbum.js, src/components/album/WriteAlbum.js, src/components/indivAlbum/WriteIndivAlbum.js, src/components/ui/ModalOneBtn.js, src/components/ui/ModalTwoBtn.js, src/pages/indivalbum/IndivAlbumDetails.js, src/pages/indivalbum/IndivAlbumList.js, src/pages/indivalbum/IndivAlbumModify.js
- 추억 앨범 글쓰기
- 유치원생 일괄 선택 및 일괄 삭제
- 유치원생 이름으로 직접 검색 또는 키보드 이벤트로 검색
- 추억 앨범 수정
- API 연동 중
- 추억 앨범 상세
- 댓글 기능 연동 중  
- 모달창 키 이벤트적용
- 확인(Enter), 취소(Esc)
=> feat : 추억앨범, 모달버튼 기능 추가 및 수정

src/api/indivAlbum/indivalbum_api.js, src/components/album/ModifyAlbum.js, src/pages/indivalbum/IndivAlbumDetails.js, src/pages/indivalbum/IndivAlbumModify.js
추억앨범 수정기능 오류 수정
댓글 수정, 삭제 시 오류 수정 중
=> fix: 추억앨범 수정기능 오류 수정
